### PR TITLE
add osx package deps

### PR DESCRIPTION
**Pull request by bcg62**
addressing #205

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/ruby_rbenv/206)

### CODE REVIEW

**Comment by bcg62** [comment]
chef documentation seems to imply homebrew_package will accept an array, testing shows otherwise

```
* homebrew_package[pkg-config, readline, gdbm, gmp, libffi, libyaml, openssl] action install
      * No candidate version available for readline, gdbm, gmp, libffi, libyaml, openssl
      ================================================================================
      Error executing action `install` on resource 'homebrew_package[pkg-config, readline, gdbm, gmp, libffi, libyaml, openssl]'
      ================================================================================

      Chef::Exceptions::Package
      -------------------------
      No candidate version available for readline, gdbm, gmp, libffi, libyaml, openssl

      Resource Declaration:
      ---------------------
      # In /var/folders/7f/9lj81yv94xb8p9_n7fntfn34xs6f50/T/cookbooks.xqm5KhWR/site-cookbooks/ruby_rbenv/resources/ruby.rb

       89:       package package_deps
       90:     end

      Compiled Resource:
      ------------------
      # Declared in /var/folders/7f/9lj81yv94xb8p9_n7fntfn34xs6f50/T/cookbooks.xqm5KhWR/site-cookbooks/ruby_rbenv/resources/ruby.rb:89:in `install_ruby_dependencies'

      homebrew_package("pkg-config, readline, gdbm, gmp, libffi, libyaml, openssl") do
        package_name ["pkg-config", "readline", "gdbm", "gmp", "libffi", "libyaml", "openssl"]
        action [:install]
        default_guard_interpreter :default
        declared_type :package
        cookbook_name :"nasdaq-ruby"
      end

      System Info:
      ------------
      chef_version=13.6.4
      platform=mac_os_x
      platform_version=10.12.6
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]
      program_name=chef-solo worker: ppid=1640;start=16:09:09;
      executable=/opt/chefdk/bin/chef-solo


    ================================================================================
    Error executing action `install` on resource 'ruby_rbenv_ruby[2.4.1]'
    ================================================================================
```

**Comment by tas50** [comment]
Yep homebrew_package hasn't been updated for multipackage installs

**Comment by bcg62** [comment]
added a workaround

**Comment by damacus** [comment]
Thanks @bcg62 

could you add some testing to this branch please?

I think this branch in the osx cookbook might do the job.

**Comment by bcg62** [comment]
Which tests are you looking for? 

I'm also encountering this 

https://github.com/chef/chef/issues/5455

```* ruby_rbenv_script[rbenv install 2.4.1 -v (user)] action run
      * bash[rbenv install 2.4.1 -v (user)] action run
        [execute] bash: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20180131-81870-1bffulf: Permission denied

        ================================================================================
        Error executing action `run` on resource 'bash[rbenv install 2.4.1 -v (user)]'
        ================================================================================

        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '126'
        ---- Begin output of "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20180131-81870-1bffulf" ----
        STDOUT:
        STDERR: bash: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20180131-81870-1bffulf: Permission denied
        ---- End output of "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20180131-81870-1bffulf" ----
        Ran "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20180131-81870-1bffulf" returned 126

        Resource Declaration:
        ---------------------
        # In /var/folders/7f/9lj81yv94xb8p9_n7fntfn34xs6f50/T/cookbooks.S2r9k2zM/site-cookbooks/ruby_rbenv/resources/script.rb

         39:   bash new_resource.name do
         40:     code script_code
         41:     user new_resource.user if new_resource.user
         42:     creates new_resource.creates if new_resource.creates
         43:     cwd new_resource.cwd if new_resource.cwd
         44:     group new_resource.group if new_resource.group
         45:     returns new_resource.returns if new_resource.returns
         46:     timeout new_resource.timeout if new_resource.timeout
         47:     umask new_resource.umask if new_resource.umask
         48:     environment(script_environment)
         49:     live_stream new_resource.live_stream
         50:   end
         51: end

        Compiled Resource:
        ------------------
        # Declared in /var/folders/7f/9lj81yv94xb8p9_n7fntfn34xs6f50/T/cookbooks.S2r9k2zM/site-cookbooks/ruby_rbenv/resources/script.rb:39:in `block in class_from_file'

        bash("rbenv install 2.4.1 -v (user)") do
          action [:run]
          default_guard_interpreter :default
          command nil
          backup 5
          environment {"RBENV_ROOT"=>"/Users/user/.rbenv", "RUBY_CONFIGURE_OPTS"=>"--with-readline-dir=\"$(brew --prefix readline)\"", "USER"=>"user", "HOME"=>"/Users/user"}
          returns [0]
          user "user"
          live_stream true
          interpreter "bash"
          declared_type :bash
          cookbook_name :"nasdaq-ruby"
          code "export RBENV_ROOT=\"/Users/user/.rbenv\"\nexport PATH=\"${RBENV_ROOT}/bin:$PATH\"\neval \"$(rbenv init -)\"\nrbenv install 2.4.1 -v\n"
          domain nil
        end

        System Info:
        ------------
        chef_version=13.6.4
        platform=mac_os_x
        platform_version=10.13.3
        ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin14]
        program_name=chef-solo worker: ppid=81868;start=14:17:44;
        executable=/opt/chefdk/bin/chef-solo

```

**Comment by damacus** [comment]
Hey @bcg62 got distracted by the other work. 

This travis.yml config should add Mac support to the cookbook.
https://github.com/sous-chefs/mac_os_x/blob/modernize-cookbook/.travis.yml

And this kitchen.yml should add the suites. 
https://github.com/sous-chefs/mac_os_x/blob/modernize-cookbook/.kitchen.yml

I think just a test that the thing even installs in Mac works. So, the user_install suite would work probably!

```yaml
- name: user_install
  run_list: recipe[test::user_install]
  includes: [centos-7.3]
```

**Comment by damacus** [comment]
Hey @bcg62 this looks pretty good still. 

Do you want to give the testing another go?

**Review by damacus — CHANGES_REQUESTED** [review]
Requires tests

**Comment by damacus** [comment]
I'd rather not fix the lack of multi package install here but upstream.

**Comment by damacus** [comment]
@tas50 does homebrew have multi package installs in Chef 14?

**Comment by tas50** [comment]
Sadly no, but fixing that is on my todo list in the next year.

**Comment by damacus** [comment]
I'm going to drop this PR for now. 

We should be fixing this up stream.

**Pull request closed without merging**
