### PR TITLE
Using libgdm6 when Debian 10.0 (#255)

### LINKED ISSUE #259: Dangerfile should use failure instead of fail
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

On the repo, ensure that `Dangerfile` matches https://github.com/sous-chefs/repo-management/blob/master/Dangerfile

Issue sprouted from sous-chefs/meta/issues/110. If not applicable then issue should be closed.

### LINKED ISSUE #261: Update Changelog
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Update all CHANGELOGs to follow standard defined at <https://keepachangelog.com/>

Issue sprouted from sous-chefs/meta/issues/101. If not applicable then issue should be closed.

### LINKED ISSUE #266: https://github.com/sous-chefs/ruby_rbenv/pull/255 not merged properly ?
## :ghost: Brief Description

Some time ago I posted https://github.com/sous-chefs/ruby_rbenv/issues/254 and in theory it was fixed in https://github.com/sous-chefs/ruby_rbenv/pull/255

But I think something went wrong with the merging, because those changes are not in `master`

## :pancakes: Cookbook version

2.1.3 

## :tophat: Platform details

Debian 10.0

### PR DESCRIPTION
**Pull request by JohnRoesler**
* Update CHANGELOG

* Using libgdm6 when Debian 10.0

# Description

Describe what this change achieves

## Issues Resolved

Closes https://github.com/sous-chefs/ruby_rbenv/issues/266
Closes https://github.com/sous-chefs/ruby_rbenv/issues/261
Actually closes https://github.com/sous-chefs/ruby_rbenv/issues/259

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/ruby_rbenv/269)

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dormi** [comment]
Thank you @JohnRoesler

**Comment by JohnRoesler** [comment]
@dormi take a look and make sure the desired changes got merged into this PR. Had some conflicts, so hopefully I got it all right!

**Comment by dormi** [comment]
@JohnRoesler yes, the desired change is present: https://github.com/sous-chefs/ruby_rbenv/pull/269/files#diff-3805d426508a9652201b34ccbcf38496
👌

**Pull request merged**
