### PR TITLE
Fix rubinius dependencies

### PR DESCRIPTION
**Pull request by sekrett**
### Description

This will fix the method undefined error.

I did not test, should be obvious.

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/ruby_rbenv/197)

### CODE REVIEW

**Comment by damacus** [comment]
hah a would you mind testing it super quickly please and I can release today.

**Comment by sekrett** [comment]
No, sorry. I don't use those OSes. I could test dependencies for FreeBSD later, because I will need that.

**Comment by willejs** [comment]
@sekrett theres this thing called ```test kitchen``` its not a new idea, and it lets you run all those OSes on your machine and run the tests to ensure it works for everyone else too! Its amazing right?! 
If not, you might want to change your profile pic to this instead

**Comment by damacus** [comment]
OK thanks. I'm going to have to close this PR as it's not tested in anyway. Even if it is the right change.

**Pull request closed without merging**
