### PR TITLE
Using libgdm6 when Debian 10.0

### PR DESCRIPTION
**Pull request by dormi**
### Description
When running `rbenv_ruby 2.4.1` on a chef recipe in Debian 10.0, I got:
```
* ruby_rbenv_plugin[ruby-build] action install
* git[Install ruby-build plugin] action sync (up to date)
   (up to date)
* apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install
* No candidate version available for libgdbm3
 ================================================================================
 Error executing action `install` on resource 'apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make]'
 ================================================================================
 
 Chef::Exceptions::Package
 -------------------------
 No candidate version available for libgdbm3
```

This PR tries to use `libdgm6` on Debian 10, which seems to work.

### Issues Resolved
https://github.com/sous-chefs/ruby_rbenv/issues/254

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/ruby_rbenv/255)

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
Hey,

thanks for the PR, can you update your PR with feedback from kitchen-porter and the linting errors please? 

Thanks!
Dan

**Comment by dormi** [comment]
Hi @damacus. I am having problems detecting the lint errors.
Where/how can I see them?

**Comment by damacus** [comment]
Ah it's just below the last comment in the Github UI. Hitting "Details" will take you to CircleCI. 

Which I just did and have realised we're on an old CircleCI orb which is causing the error. I'll get that fixed up so you can rebase on something sensible. Sorry about that! 

With 70+ repos there's always something needing updating!

**Comment by damacus** [comment]
Fixed! thank you for this, I'll get this released shortly.

**Comment by dormi** [comment]
@damacus a `2.1.3` version was released, but does not contain this `libgdm6` update?

**Comment by dormi** [comment]
^ ping @damacus

**Comment by francocatena** [comment]
I get this error too, aparently the fix is not released because it is in another branch (debug-circleci-failures).

Presumibly it needs some love, but the problem is we can not get this working on Debian 10 since there is no way around it if not released.

There is something we can do to help this?

**Pull request merged**
