### PR TITLE
Missing requires in chef_provider_package_rbenvrubygems.rb

### PR DESCRIPTION
**Pull request by gregkare**
Fixes the following problem:

```
NameError: uninitialized constant Chef::Rbenv
```

### CODE REVIEW

**Comment by fnichol** [comment]
Look like this has come up a couple of times now. I had this issue in a couple of other cookbooks due to the way/order that Chef loads in libraries/ code. Are you able to double check if the above patch gets the job done? Thanks!

**Comment by fnichol** [comment]
I'm assuming we've addressed this issue. Thank you!

**Comment by gregkare** [comment]
Sorry about the delay, I completely forgot about your message! Your solution works as well, I finally got around to trying it.

**Comment by fnichol** [comment]
No problem, I know what that's like :)

**Pull request closed without merging**
