### PR TITLE
[chef 12] Use full class name for rbenv_rehash resource

### LINKED ISSUE #98: [Chef 12.0.0] undefined method rbenv_rehash for Chef::Provider::Package::RbenvRubygems
Run the following commands:

```
git clone git@github.com:aminin/rbenv-fail-chef-12.git
cd rbenv-fail-chef-12
bundle install
bundle exec librarian-chef install
vagrant up
vagrant ssh -c 'wget https://www.getchef.com/chef/install.sh'
#11.16.4 works fine
# vagrant ssh -c 'sudo bash install.sh -v 11.16.4'
vagrant ssh -c 'sudo bash install.sh -v 12.0.0'
vagrant provision
```

The above script  results in error: undefined method rbenv_rehash.

System info:
Ubuntu 14.04
Vagrant 1.6.3
VirtualBox 4.3.14r95030
ruby 1.9.3p484

### PR DESCRIPTION
**Pull request by aminin**
fixes #98

### CODE REVIEW

**Comment by josacar** [comment]
@fnichol Any plans on merging this?

**Comment by zhiyuanshi** [comment]
I'm also experiencing the issue that motivates this merge. It would be nice if this can be soon merged into upstream.

Why are the tests failing?

**Comment by washingtoneg** [comment]
@aminin, wouldn't this require a version bump?

**Comment by aminin** [comment]
@washingtoneg, version bump? what do you mean? This cookbook version is 0.7.3 for the last two years.

**Comment by washingtoneg** [comment]
@aminin, I'm just wondering if this would potentially be a breaking change that would be incompatible with previous versions of chef server. If so, that would warrant a version bump, in my opinion. Thoughts?

**Comment by aminin** [comment]
Installation from supermarket.chef.io is the only rational reason for using SemanticVersion in CookBook.
Unfortunately coockbook name `rbenv` on supermarket is reserved by another CB (less convenient analog).

On github you may always use sha1 instead  of SV.

**Comment by washingtoneg** [comment]
That makes complete sense and I agree with your standpoint.

**Comment by bplunkert** [comment]
Hi @aminin, thanks for this change, it totally fixes the issue for me. I noticed there are a few other changes here as well: removing Gemfile.lock from .gitignore, and it looks like RVM is added in as well. Those seem like bigger changes to me.

As I just want to get running in as simple and forward-compatible manner as possible, I tested with only your change to `libraries/chef_provider_package_rbenvrubygems.rb` and that worked great. For reference: [bplunkert:fix_rbhash_undefined_method](https://github.com/fnichol/chef-rbenv/compare/master...bplunkert:fix_rbhash_undefined_method?expand=1)

So I opened up #108 hopefully that helps get the fix merged!

**Comment by aminin** [comment]
@bplunkert, the Gemfile.lock only makes travis CI build pass. It doesn't affect your production chef version (or another gem version).

**Comment by CloCkWeRX** [comment]
I've applied a version of this to my fork (well https://github.com/aminin/chef-rbenv/commit/16bbb2e4d34a63261e95368ee4d648cd03ad9c85 at least)

**Comment by CloCkWeRX** [comment]
Fixed on master

**Pull request closed without merging**
