### PR TITLE
Add support for rbenv plugins

### PR DESCRIPTION
**Pull request by jasherai**
I've added support for rbenv plugins. I have done this via the existing rbenv installation library rather than a new one or a provider.

@fnichol not sure if this is something you want in here?

### CODE REVIEW

**Comment by jasherai** [comment]
@fnichol is this something you might want in here?

**Comment by wingrunr21** [comment]
This feature would be useful for those of us who run rbx. Automatically installing [rbenv-rbx](https://github.com/rmm5t/rbenv-rbx) would be awesome.

**Comment by poblahblahblah** [comment]
+1

**Comment by johnbellone** [comment]
+1 here. Definitely would help me out a lot since I have to setup Oracle drivers and rbenv-vars is great!

**Comment by fleadope** [comment]
+1

**Comment by johnbellone** [comment]
@fnichol Any interest?

**Comment by ggayan** [comment]
+1, using this with [sprout](https://github.com/pivotal-sprout/sprout) would be awesome

**Comment by cubranic** [comment]
Can this now be closed?

**Pull request merged**
