### PR TITLE
Set dependencies properly for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by joshsymonds**
Ruby requires some different dependencies for installation in Ubuntu 20.04 -- this PR provides them, and adds Ubuntu 20.04 as a target for test kitchen.

### CODE REVIEW

**Comment by xorima** [comment]
Hey @Veraticus 

To add ubuntu 20.04 to testing you will also need to go into the `.github/workflows/ci.yml` and add it to the matrix there

Thanks for this

**Comment by joshsymonds** [comment]
Done! It seems like one of the checks still isn't running properly -- not sure if that's an issue on my end?

**Comment by joshsymonds** [comment]
Hey @Xorima, anything else you want me to do here? :)

**Comment by ramereth** [comment]
@Veraticus can you please update your branch to match current master and see if the test failures go away?

**Comment by xorima** [comment]
Error is with cookbook not this code, we have no spec tests yet we are trying to run them

**Pull request merged**
